name: Build LaTeX document
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          # Enable this if you need to use biber for references
          latexmk_shell_escape: true
          extra_system_packages: "biber"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: main.pdf

      # Optional: Release the PDF if a tag is pushed
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 